import type { ViatorProduct, ViatorAttraction } from "./types";

export const DEMO_PRODUCTS: ViatorProduct[] = [
  {
    productCode: "DEMO-001",
    provider: "viator",
    title: "Lisbon Spa & Hammam Experience",
    description: "Relax in a traditional hammam with aromatherapy, hot stone massage, and tea ceremony in a beautifully restored Moorish bathhouse.",
    reviews: { combinedAverageRating: 4.7, totalReviews: 312 },
    pricing: { summary: { fromPrice: 65 }, currency: "EUR" },
    duration: { fixedDurationInMinutes: 120 },
    tags: [21911],
    productUrl: "https://www.viator.com/tours/Lisbon/Spa-Hammam-Experience/d538-DEMO001",
    flags: [],
    images: [{ variants: [{ url: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400&h=300&fit=crop" }] }],
  },
  {
    productCode: "DEMO-002",
    provider: "viator",
    title: "Wellness Retreat in Sintra with Wine Tasting",
    description: "Escape to Sintra for a half-day wellness retreat, with yoga, guided meditation, organic lunch and wine tasting at a palace vineyard.",
    reviews: { combinedAverageRating: 4.9, totalReviews: 87 },
    pricing: { summary: { fromPrice: 120 }, currency: "EUR" },
    duration: { fixedDurationInMinutes: 300 },
    tags: [21911, 21480],
    productUrl: "https://www.viator.com/tours/Lisbon/Wellness-Sintra/d538-DEMO002",
    flags: [],
    images: [{ variants: [{ url: "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=400&h=300&fit=crop" }] }],
  },
  {
    productCode: "DEMO-003",
    provider: "viator",
    title: "Alfama Rooftop Yoga & Brunch",
    description: "Morning yoga on a panoramic rooftop overlooking the Tagus River, followed by a healthy brunch with local pastries.",
    reviews: { combinedAverageRating: 4.8, totalReviews: 156 },
    pricing: { summary: { fromPrice: 45 }, currency: "EUR" },
    duration: { fixedDurationInMinutes: 150 },
    tags: [21911],
    productUrl: "https://www.viator.com/tours/Lisbon/Rooftop-Yoga/d538-DEMO003",
    flags: [],
    images: [{ variants: [{ url: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&h=300&fit=crop" }] }],
  },
  {
    productCode: "DEMO-004",
    provider: "viator",
    title: "Portuguese Thermal Baths Day Trip",
    description: "Visit the famous natural thermal springs outside Lisbon, with transfers, towel service, and a traditional Portuguese lunch.",
    reviews: { combinedAverageRating: 4.5, totalReviews: 203 },
    pricing: { summary: { fromPrice: 89 }, currency: "EUR" },
    duration: { fixedDurationInMinutes: 480 },
    tags: [21911],
    productUrl: "https://www.viator.com/tours/Lisbon/Thermal-Baths/d538-DEMO004",
    flags: [],
    images: [{ variants: [{ url: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=400&h=300&fit=crop" }] }],
  },
  {
    productCode: "DEMO-005",
    provider: "viator",
    title: "Sunset Sailing & Meditation on the Tagus",
    description: "Sail along the Tagus River at sunset with a guided meditation session, champagne, and Portuguese cheese board.",
    reviews: { combinedAverageRating: 4.6, totalReviews: 98 },
    pricing: { summary: { fromPrice: 75 }, currency: "EUR" },
    duration: { fixedDurationInMinutes: 120 },
    tags: [21911, 20246],
    productUrl: "https://www.viator.com/tours/Lisbon/Sunset-Sailing/d538-DEMO005",
    flags: [],
    images: [{ variants: [{ url: "https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?w=400&h=300&fit=crop" }] }],
  },
  {
    productCode: "DEMO-006",
    provider: "viator",
    title: "Luxury Facial & Azulejo Tile Workshop",
    description: "Combine a luxury facial using Portuguese botanical products with a hands-on azulejo tile painting workshop.",
    reviews: { combinedAverageRating: 4.4, totalReviews: 67 },
    pricing: { summary: { fromPrice: 95 }, currency: "EUR" },
    duration: { fixedDurationInMinutes: 240 },
    tags: [21911, 21915],
    productUrl: "https://www.viator.com/tours/Lisbon/Facial-Tile-Workshop/d538-DEMO006",
    flags: [],
    images: [{ variants: [{ url: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=400&h=300&fit=crop" }] }],
  },
];

export const DEMO_ATTRACTIONS: ViatorAttraction[] = [
  {
    attractionId: 90001,
    name: "Jerónimos Monastery",
    reviews: { combinedAverageRating: 4.8, totalReviews: 4521 },
    productCount: 23,
  },
  {
    attractionId: 90002,
    name: "Belém Tower",
    reviews: { combinedAverageRating: 4.6, totalReviews: 3210 },
    productCount: 18,
  },
  {
    attractionId: 90003,
    name: "Sintra National Palace",
    reviews: { combinedAverageRating: 4.7, totalReviews: 2890 },
    productCount: 31,
  },
];
